export const REQUEST_BALANCE_INFO = 'REQUEST_BALANCE_INFO'
export const RECEIVE_BALANCE_INFO = 'RECEIVE_BALANCE_INFO'

export const REQUEST_BALANCE_ORDER = 'REQUEST_BALANCE_ORDER'
export const RECEIVE_BALANCE_ORDER = 'RECEIVE_BALANCE_ORDER'
