export const REQUEST_CART = 'REQUEST_CART'
export const RECEIVE_CART = 'RECEIVE_CART'

export const REQUEST_DEL_CART = 'REQUEST_DEL_CART'
export const RECEIVE_DEL_CART = 'RECEIVE_DEL_CART'

export const REQUEST_CHANGE_NUM = 'REQUEST_CHANGE_NUM'
export const RECEIVE_CHANGE_NUM = 'RECEIVE_CHANGE_NUM'

export const REQUEST_CHECK_CART = 'REQUEST_CHECK_CART'
export const RECEIVE_CHECK_CART = 'RECEIVE_CHECK_CART'

export const REQUEST_INVERSE_CHECK = 'REQUEST_INVERSE_CHECK'
export const RECEIVE_INVERSE_CHECK = 'RECEIVE_INVERSE_CHECK'

export const REQUEST_SKU_ATTR = 'REQUEST_SKU_ATTR'
export const RECEIVE_SKU_ATTR = 'RECEIVE_SKU_ATTR'

export const REQUEST_CHANGE_ATTR = 'REQUEST_CHANGE_ATTR'
export const RECEIVE_CHANGE_ATTR = 'RECEIVE_CHANGE_ATTR'

export const CHECK_DEL = 'CHECK_DEL'
export const INVERSE_CHECK_DEL = 'INVERSE_CHECK_DEL'

export const SHOW_ATTR_BOX = 'SHOW_ATTR_BOX'
export const HIDE_ATTR_BOX = 'HIDE_ATTR_BOX'

export const CHANGE_EDIT_STATUS = 'CHANGE_EDIT_STATUS'

export const operate = {
  QUERY: '1',
  ADD: '2',
  CHANGE_NUM: '3',
  DEL: '4',
  CHECK: '5',
  INVERT_CHECK: '6',
  CHANGE_ATTR: '8',
  GET_NUM: '9'
}
