export const REQUEST_DETAIL_CART = 'REQUEST_DETAIL_CART'
export const RECEIVE_DETAIL_CART = 'RECEIVE_DETAIL_CART'

export const REQUEST_DETAIL_SKU = 'REQUEST_DETAIL_SKU'
export const RECEIVE_DETAIL_SKU = 'RECEIVE_DETAIL_SKU'

export const REQUEST_DETAIL_ADD_CART = 'REQUEST_DETAIL_ADD_CART'
export const RECEIVE_DETAIL_ADD_CART = 'RECEIVE_DETAIL_ADD_CART'

// export const REQUEST_CART = 'REQUEST_CART'
// export const RECEIVE_CART = 'RECEIVE_CART'

// export const REQUEST_CART = 'REQUEST_CART'
// export const RECEIVE_CART = 'RECEIVE_CART'
