
export const SHOW_SEARCH_BAR = 'SHOW_SEARCH_BAR'
export const REQUEST_SEARCH_RESULT = 'REQUEST_SEARCH_RESULT'
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT'
export const RECEIVE_SEARCH_ERROR = 'RECEIVE_SEARCH_ERROR'
export const SHOW_RESULT = 'SHOW_RESULT'
export const CHANGE_HISTORY = 'CHANGE_HISTORY'
export const SHOW_NOT_FIND = 'SHOW_NOT_FIND'
export const RESET_STATE = 'RESET_STATE'
