export const REQUEST_ORDER_DETAIL = 'REQUEST_ORDER_DETAIL'
export const RECEIVE_ORDER_DETAIL = 'RECEIVE_ORDER_DETAIL'
export const RESET_ORDER_DETAIL = 'RESET_ORDER_DETAIL'

export const REQUEST_ORDER_CANCEL = 'REQUEST_ORDER_CANCEL'
export const RECEIVE_ORDER_CANCEL = 'RECEIVE_ORDER_CANCEL'
